
version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: story
      POSTGRES_PASSWORD: story
      POSTGRES_DB: storymaker
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6380:6379"]
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: story
      MINIO_ROOT_PASSWORD: storysecret
    ports: ["9000:9000","9001:9001"]
    volumes: [ "minio:/data" ]
volumes: { minio: {} }
