name: Verify
on:
  push:
  pull_request:
jobs:
  guards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run guards
        run: |
          chmod +x ci/*.sh || true
          make rules-sync
          make verify
