#!/usr/bin/env bash
set -euo pipefail
root="$(git rev-parse --show-toplevel)"
ws="$root/.agentpm_workspace"

make_stub() {
  local tgt="$1" ; local rel="$2"
  mkdir -p "$(dirname "$tgt")"
  cat >"$tgt" <<EOF
# Pointer: Single Source of Truth
This file intentionally points to the canonical document.
See: $rel
Do not edit this file directly. Update the canonical source in the main repo.
EOF
  echo "::notice ::wrote pointer $tgt → $rel"
}

# 1) Workspace root AGENTS.md → docs/AGENTS.md
if [ -f "$ws/AGENTS.md" ]; then
  make_stub "$ws/AGENTS.md" "../docs/AGENTS.md"
fi

# 2) All AGENTS.md files in workspace → convert to pointer stubs
# Find all AGENTS.md files in workspace and convert them to pointers
find "$ws" -name "AGENTS.md" -type f | while read -r f; do
  # Skip if already a pointer stub
  if head -n1 "$f" | grep -q '^# Pointer: Single Source of Truth'; then
    continue
  fi
  
  # Calculate relative path to main repo
  rel_path="${f#$ws/}"
  rel_path="../$rel_path"
  
  # Convert to pointer stub
  make_stub "$f" "$rel_path"
done

echo "agents_pointerize: OK"
