#!/usr/bin/env bash
set -euo pipefail

root="$(git rev-parse --show-toplevel)"
canon_dir="$root/docs/SSOT"
agent_dir="$root/.agentpm_workspace/docs/SSOT"

mkdir -p "$agent_dir"
for f in MASTER_PLAN.md VALIDATION_PROTOCOL.md DRIFT_LOG.md; do
  canon="$canon_dir/$f"
  agent="$agent_dir/$f"
  [ -f "$canon" ] || { echo "::error ::missing $canon"; exit 1; }
  if [ ! -f "$agent" ] || ! grep -q '^# Pointer: Single Source of Truth' "$agent"; then
    cat >"$agent" <<EOF
# Pointer: Single Source of Truth
This file intentionally points to the canonical document.
See: ../../docs/SSOT/$f (resolved via docs/SSOT/ssot.locator)
Do not edit this file directly. Update the canonical source and run \`make ssot.sync.docs\`.
EOF
    echo "::notice ::wrote pointer $agent"
  fi
done
echo "ssot_docs_sync ok"


