
name: OpenAPI Validate
on:
  push: { paths: ['docs/openapi/**', '.redocly.yaml'] }
  pull_request: { paths: ['docs/openapi/**', '.redocly.yaml'] }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm i -g @redocly/cli
      - run: redocly lint --format=stylish .redocly.yaml || true
